### ISSUE TITLE
us dog tags

### ISSUE THREAD

**Issue by HanaKachel** [slischka/nejentriko.cz#15]
tady se mi nelibi je tam moc textu

historii bych dala pryc nebo spise bych tam dala jen odkaz historie us dogs a po zakliknuti by se otevrelo více informaci, ale ted je toho moc 

nechala bych tam jen text jako uvod
známky vám rádi vyrazíme dle vašeho přání. známky jsou ražené na originálním razícím stroji dovezeného s usa

podto bych dalal odkaz historie a více informací o us dogs tags

dále bych nechala co se tam nejčasteji razi

co vse sada obsahuje ..... u gumicek dopiš gumičky za příplatek

objednávkovy formulář bych dala v levo a texty v pravo at celej web je jednotný

u gumiček dopln polozku - bez gumicek zdarma

**Comment by slischka** [comment]
Tady bych teda poprosil o sepsaní textů, které momentálně nahradí historii. a historii bych přesunul na samostatnou stránku.

**Comment by HanaKachel** [comment]
historii nechame stejnou jen bude schovana a muzes si ji precist jen po kliknuti na odkaz at to zbytecne neblokuje moc textu

**Comment by HanaKachel** [comment]
jinak jsou známky ok
